on:
  workflow_call:

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-13
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools
      - name: Install coverage tools
        run: cargo install cargo-llvm-cov
      - name: Build and test with coverage
        run: cargo llvm-cov --include-build-script --doctests --branch --all-features --workspace --html
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: target/llvm-cov/html
  deploy:
    name: Deploy
    needs: coverage
    if: github.ref == 'refs/heads/develop'
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage
      - name: Upload web archive
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage
      - name: Deploy pages
        uses: actions/deploy-pages@v4
